//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explicacion_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int IdStock { get; set; }
        public string Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Proveedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
